joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
    
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
    - Joint_5
    - Joint_6
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_a1: {trajectory: 0.1, goal: 0.1}
    joint_a2: {trajectory: 0.1, goal: 0.1}
    joint_a3: {trajectory: 0.1, goal: 0.1}
    joint_a4: {trajectory: 0.1, goal: 0.1}
    joint_a5: {trajectory: 0.1, goal: 0.1}
    joint_a6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
